# Generated by Django 4.2.4 on 2023-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('current_status', models.DateTimeField(auto_now_add=True)),
                ('barrowing_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
