# Generated by Django 4.2.4 on 2023-12-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patron_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('membership_details', models.CharField(max_length=100)),
                ('card_number', models.IntegerField()),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book_management')),
            ],
        ),
        migrations.CreateModel(
            name='book_borroewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_date', models.DateTimeField(auto_now_add=True)),
                ('retun_date', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.patron_management')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book_management')),
            ],
        ),
    ]
